### PR TITLE
Breaking change: configure the wiki URL instead of confluence domain

### PR DESCRIPTION
**Pull request by K-Phoen**

### CODE REVIEW

**Comment by K-Phoen** [comment]
@satrox28 do you still need something like this PR or could you make it work without?

**Comment by satrox28** [comment]
Confluence urls not mandate to have /wiki. I feel it's better to let users configure the full url from the app-config.yaml

**Comment by satrox28** [comment]
Hi @K-Phoen any update on this PR?.

**Comment by satrox28** [comment]
@K-Phoen will you be merging this changes?.

**Comment by satrox28** [comment]
@K-Phoen  can it be released?.

**Comment by K-Phoen** [comment]
@satrox28 Yes, I will be merging this.

One thing I would like to voice though: unless I am [sponsored by an individual or a company](https://github.com/sponsors/K-Phoen), I work on this plugin on my own time. If and when I have time. If and when I feel like it.

Pinging me repeatedly on a PR does not help. I hope you will understand my position :)

**Pull request merged**
